scireum_volumes: &scireum_volumes
  - /var/run/docker.sock:/var/run/docker.sock
  - /var/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:/drone/src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
  - /root/.m2:/root/.m2
  - /root/.gnupg:/root/.gnupg
  - /root/.ssh:/root/.ssh
clone:
  git:
    image: plugins/git
    volumes: *scireum_volumes
pipeline:
  compile:
    image: scireum/sirius-build
    commands:
      - mvn clean compile
    volumes: *scireum_volumes
    when:
      event: push
  test:
    image: scireum/sirius-build
    commands:
      - mvn clean test
    volumes: *scireum_volumes
    when:
      event: pull_request
  sonar:
    image: scireum/sirius-build
    commands:
      - sed -i 's/DEVELOPMENT-SNAPSHOT/${DRONE_TAG}/g' pom.xml
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Dsonar.projectKey=${DRONE_REPO_NAME}
    volumes: *scireum_volumes
    when:
      event: tag
  package:
    image: scireum/sirius-build
    commands:
      - sed -i 's/DEVELOPMENT-SNAPSHOT/${DRONE_TAG}/g' pom.xml
      - mvn clean package -DskipTests
    volumes: *scireum_volumes
    when:
      event: tag
  publish:
    image: plugins/docker
    repo: scireum/s3-ninja
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    volumes: *scireum_volumes
    when:
      event: tag
  site:
    image: scireum/sirius-build
    commands:
      - rsync -r --delete src/site/ ssh-w0158395@w0158395.kasserver.com:/www/htdocs/w0158395/s3ninja.net/
    volumes: *scireum_volumes
    when:
      event: tag
