<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.scireum</groupId>
        <artifactId>sirius-parent</artifactId>
        <version>17.0.1</version>
    </parent>

    <artifactId>s3ninja</artifactId>
    <version>DEVELOPMENT-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>s3-ninja</name>
    <description>S3 ninja emulates the S3 API for development and testing purposes.</description>
    <url>https://s3ninja.net</url>

    <properties>
        <build.tag>DEVELOPMENT-SNAPSHOT</build.tag>

        <sirius.kernel>54.2.0</sirius.kernel>
        <sirius.web>109.4.0</sirius.web>

        <!-- Force build to complete with warnings, e.g.: while using deprecated code -->
        <maven.compiler.warnings></maven.compiler.warnings>
        <maven.javadoc.skip>true</maven.javadoc.skip>
        <source.skip>true</source.skip>
    </properties>

    <pluginRepositories>
        <pluginRepository>
            <id>scireum-mvn</id>
            <url>https://mvn.scireum.com</url>
        </pluginRepository>
    </pluginRepositories>

    <repositories>
        <repository>
            <id>scireum-mvn</id>
            <url>https://mvn.scireum.com</url>
        </repository>
    </repositories>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*.conf</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>**/*.conf</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>src/main/resources/constants</directory>
                <filtering>false</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.scireum</groupId>
            <artifactId>sirius-kernel</artifactId>
            <version>${sirius.kernel}</version>
        </dependency>
        <dependency>
            <groupId>com.scireum</groupId>
            <artifactId>sirius-kernel</artifactId>
            <version>${sirius.kernel}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.scireum</groupId>
            <artifactId>sirius-web</artifactId>
            <version>${sirius.web}</version>
        </dependency>
        <dependency>
            <groupId>com.scireum</groupId>
            <artifactId>sirius-web</artifactId>
            <version>${sirius.web}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3-transfer-manager</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>2.54.13</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
